import type { Metadata } from "next";
import Header from "../ui/adminHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
      //el div que envuelve children hace que ya no se vea un espacio blanco en la pag principal

      <>
          <Header />
            <div className="flex flex-col overflow-y-auto min-h-screen">
                {children}

            </div>
          
          
        </>
    
        
  );
}