import type { Metadata } from "next";
import Header from "../ui/adminHeader";
import { logOut } from "../lib/actions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
      //el div que envuelve children hace que ya no se vea un espacio blanco en la pag principal

      <>
          <Header />
            <div className="flex flex-col overflow-y-auto min-h-screen bg-gradient-to-r from-gray-200 to-gray-400">
                {children}

                <form action={logOut}>
                    <button className="ml-8 mb-8 rounded-md bg-black p-4 text-lg font-medium text-white hover:bg-blue-600 hover:text-black">
                        <div>Sign Out</div>
                    </button>
                </form>

            </div>
          
          
        </>
    
        
  );
}