import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../ui/topNav";
import { CartProvider } from "../contexts/cartContext";
import { AlbumProvider } from "../contexts/albumContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
      //el div que envuelve children hace que ya no se vea un espacio blanco en la pag principal

      <>
          <Header />
          <AlbumProvider>
            <CartProvider>
              <div className="flex flex-col overflow-y-auto min-h-screen">
                {children}
              </div>
            </CartProvider>
          </AlbumProvider>
          
        </>
    
        
  );
}